{"name":"verifyUserCannotLoginWithIncorrectCredentials","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"The Введены неверные данные error should be shown expected [Введены неверные данные] but found []","trace":"java.lang.AssertionError: The Введены неверные данные error should be shown expected [Введены неверные данные] but found []\n\tat org.testng.Assert.fail(Assert.java:110)\n\tat org.testng.Assert.failNotEquals(Assert.java:1413)\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:149)\n\tat org.testng.Assert.assertEquals(Assert.java:131)\n\tat org.testng.Assert.assertEquals(Assert.java:655)\n\tat autorisation_feature.VerifyLoginTest.verifyUserCannotLoginWithIncorrectCredentials(VerifyLoginTest.java:16)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:806)\n\tat org.testng.TestRunner.run(TestRunner.java:601)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:433)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:330)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1176)\n\tat org.testng.TestNG.runSuites(TestNG.java:1099)\n\tat org.testng.TestNG.run(TestNG.java:1067)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1701971005768,"stop":1701971013512,"uuid":"22b736ba-4fc0-45a7-ba79-1f5f8a6d3ace","historyId":"b679edc68b861dc11238d880f93bf680","fullName":"autorisation_feature.VerifyLoginTest.verifyUserCannotLoginWithIncorrectCredentials","labels":[{"name":"package","value":"autorisation_feature.VerifyLoginTest"},{"name":"testClass","value":"autorisation_feature.VerifyLoginTest"},{"name":"testMethod","value":"verifyUserCannotLoginWithIncorrectCredentials"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"test-task"},{"name":"subSuite","value":"autorisation_feature.VerifyLoginTest"},{"name":"host","value":"Air-office.netis.cc"},{"name":"thread","value":"1344@Air-office.netis.cc.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[{"name":"5","type":"tms"}]}